
---
name: CI/CD
on:
  push:
    branches:
      - develop
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  pre-commit:
    name: Verify the pre-commit framework was used properly by developers
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3.5.2

      - name: Set up Python
        uses: actions/setup-python@v4.6.0
        with:
          # Semantic version range syntax (like 3.x) or the exact Python version
          python-version: '3.11.0'

      - name: Run pre-commit framework as the developer should run it
        run: |
          chmod +x ./scripts/install.sh
          chmod +x ./scripts/run.sh
          ./scripts/install.sh
          ./scripts/run.sh
        shell: bash

      - name: The `git diff` showing whether the pre-commit mandated extra changes to the repository files
        if: failure()
        run: git diff

  checkov:
    name: Scan Terraform code with Checkov
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          compact: true
          soft_fail: true
          quiet: true # display only failed checks
